# Generated by Django 4.1.7 on 2023-05-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emlak',
            table='Emlak',
        ),
        migrations.AlterModelTable(
            name='i̇şletme',
            table='İşletme',
        ),
        migrations.AlterModelTable(
            name='kiralama',
            table='Kiralama',
        ),
        migrations.AlterModelTable(
            name='oyun',
            table='Oyun',
        ),
        migrations.AlterModelTable(
            name='satış',
            table='Satış',
        ),
        migrations.AlterModelTable(
            name='çalışma',
            table='Çalışma',
        ),
    ]
