# Generated by Django 4.1.7 on 2023-05-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0002_alter_emlak_table_alter_i̇şletme_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alan',
            name='emlak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.emlak'),
        ),
        migrations.AddField(
            model_name='alan',
            name='işletme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.i̇şletme'),
        ),
        migrations.AddField(
            model_name='alan',
            name='yöneticiİşletme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.yöneticii̇şletme'),
        ),
        migrations.AddField(
            model_name='oyun',
            name='grid',
            field=models.TextField(null=True),
        ),
    ]
