# Generated by Django 4.1.7 on 2023-05-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0003_alan_emlak_alan_işletme_alan_yöneticii̇şletme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alan',
            name='oyun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.oyun'),
        ),
        migrations.AlterField(
            model_name='alan',
            name='alanNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oyun',
            name='grid',
            field=models.TextField(default=''),
        ),
    ]
