# Generated by Django 4.1.7 on 2023-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0004_alan_oyun_alter_alan_alanno_alter_oyun_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alan',
            name='alanTürü',
            field=models.IntegerField(default=0),
        ),
    ]
