# Generated by Django 4.1.7 on 2023-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0007_oyun_günsayısı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇şletme',
            name='işletmeKiralamaFiyatı',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='i̇şletme',
            name='işletmeSatışFiyatı',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='i̇şletme',
            name='işletmeSeviyesi',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AlterField(
            model_name='i̇şletme',
            name='mevcutSeviyeBaşlangıçTarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
