# Generated by Django 4.1.7 on 2023-05-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0008_alter_i̇şletme_işletmekiralamafiyatı_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇şletme',
            name='işletmeSahibi',
        ),
    ]
