# Generated by Django 4.1.7 on 2023-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0009_remove_i̇şletme_işletmesahibi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alan',
            name='emlak',
        ),
        migrations.AlterField(
            model_name='i̇şletme',
            name='ürünÜcreti',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Emlak',
        ),
    ]
