# Generated by Django 4.1.7 on 2023-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0010_remove_alan_emlak_alter_i̇şletme_ürünücreti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇şletme',
            name='emlakİşletmeler',
            field=models.ManyToManyField(blank=True, related_name='satılacakİşletmeler', to='mlGame.alan'),
        ),
        migrations.DeleteModel(
            name='Kiralama',
        ),
    ]
