# Generated by Django 4.1.7 on 2023-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0011_i̇şletme_emlaki̇şletmeler_delete_kiralama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇şletme',
            name='işletmeKiralamaFiyatı',
        ),
        migrations.AlterField(
            model_name='i̇şletme',
            name='işletmeTürü',
            field=models.CharField(choices=[('Mağaza', 'Mağaza'), ('Market', 'Market'), ('Emlak', 'Emlak')], max_length=50),
        ),
    ]
