# Generated by Django 4.1.7 on 2023-05-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0012_remove_i̇şletme_işletmekiralamafiyatı_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satış',
            name='işletme',
        ),
        migrations.AddField(
            model_name='satış',
            name='alan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.alan'),
        ),
        migrations.AddField(
            model_name='satış',
            name='satanKişi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satanKişi', to='mlGame.kullanıcı'),
        ),
        migrations.AlterField(
            model_name='satış',
            name='satılanKişi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satılanKişi', to='mlGame.kullanıcı'),
        ),
    ]
