# Generated by Django 4.1.7 on 2023-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0013_remove_satış_işletme_satış_alan_satış_satankişi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇şletme',
            name='çalışmaÜcreti',
            field=models.IntegerField(default=1),
        ),
    ]
