# Generated by Django 4.1.7 on 2023-05-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0014_i̇şletme_çalışmaücreti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='çalışma',
            name='çalışmaSaatleri',
        ),
        migrations.AddField(
            model_name='çalışma',
            name='oyun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.oyun'),
        ),
    ]
