# Generated by Django 4.1.7 on 2023-05-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0015_remove_çalışma_çalışmasaatleri_çalışma_oyun'),
    ]

    operations = [
        migrations.AddField(
            model_name='satış',
            name='oyun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.oyun'),
        ),
    ]
