# Generated by Django 4.1.7 on 2023-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0017_kullanıcı_oyun'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyun',
            name='çalışmaÜcreti',
            field=models.IntegerField(default=1),
        ),
    ]
