# Generated by Django 4.1.7 on 2023-05-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0019_yöneticii̇şletme_oyun'),
    ]

    operations = [
        migrations.AddField(
            model_name='çalışma',
            name='yöneticiİşletme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.yöneticii̇şletme'),
        ),
        migrations.AlterField(
            model_name='çalışma',
            name='işletme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlGame.i̇şletme'),
        ),
    ]
