# Generated by Django 4.1.7 on 2023-05-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlGame', '0020_çalışma_yöneticii̇şletme_alter_çalışma_işletme'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alan',
            table='MLAlan',
        ),
        migrations.AlterModelTable(
            name='i̇şletme',
            table='MLİşletme',
        ),
        migrations.AlterModelTable(
            name='kullanıcı',
            table='MLKullanıcı',
        ),
        migrations.AlterModelTable(
            name='oyun',
            table='MLOyun',
        ),
        migrations.AlterModelTable(
            name='satış',
            table='MLSatış',
        ),
        migrations.AlterModelTable(
            name='yöneticii̇şletme',
            table='MLYöneticiİşletme',
        ),
        migrations.AlterModelTable(
            name='çalışma',
            table='MLÇalışma',
        ),
    ]
